### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-kubernetes-microprofile-health#2]
**Add health check...**
- [x] `name` displays a greeting and ~~displays~~ its container name

**Configure readiness and liveness probes**
- [ ] ... has a status code of at least `200` and less than `400`
_Is there a cleaner way to write this?Perhaps a status code between `200` and `400`?_

**Deploy name and ping**
- [x] Specify the default hostnames based on Windows/Mac or Linux environments like you did in kube-intro 

**Trigger restart in name microservice**
- [x] ... to "kill" it
 _This part seems a little awkward, is there a more technical term like **terminate** that you could use?_
- [x] Maybe adding a `curl -X POST http://...` command would help but I understand not all users may have curl (same for making POST twice in the next section)

**Trigger restart in name micro service and observe effects on ping microservice**
- [x] .. make the request again until you see **that** the second...
- [x] .. You will notice the `ping` pods ... 
_Missing ` around ping_
- [x] ... Note the `ping` pod... 
_Missing ` around ping_

**Comment by proubatsis** [comment]
PR Merged
